server:
  port: 8301
spring:
  application:
    name: borrowservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.164.194:3306/mac
    username: mac
    password: mactest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
