server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.164.194:3306/mac
    username: mac
    password: mactest
  # 应用名称 borrowservice
  application:
    name: borrowservice
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        # 将ephemeral修改为false，表示非临时实例（用于持续监控）
        ephemeral: false
        cluster-name: Chengdu
    loadbalancer:
      nacos:
        enabled: true
seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      # 使用Seata的命名空间，这样才能正确找到Seata服务，由于组使用的是SEATA_GROUP，配置默认值就是，就不用配了
      namespace: c0495138-b5b3-440d-8f1c-dc8cc9ba5fbc
      username: nacos
      password: nacos
  # 配置
  config:
    type: nacos
    nacos:
      namespace: c0495138-b5b3-440d-8f1c-dc8cc9ba5fbc
      username: nacos
      password: nacos
