spring:
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      # 使用Seata的命名空间，这样才能正确找到Seata服务，由于组使用的是SEATA_GROUP，配置默认值就是，就不用配了
      namespace: c0495138-b5b3-440d-8f1c-dc8cc9ba5fbc
      username: nacos
      password: nacos
  # 配置
  config:
    type: nacos
    nacos:
      namespace: c0495138-b5b3-440d-8f1c-dc8cc9ba5fbc
      username: nacos
      password: nacos
