server:
  port: 8801
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka01
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka02:8802/eureka, http://eureka01:8801/eureka
  server:
    enable-self-preservation: false

